// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbhYlsfne-z6YCq4_0-Sr0CmIYpKGTHO0',
    appId: '1:1054618276163:web:6ae9a549177295e4371ff6',
    messagingSenderId: '1054618276163',
    projectId: 'project-wisata-47148',
    authDomain: 'project-wisata-47148.firebaseapp.com',
    storageBucket: 'project-wisata-47148.firebasestorage.app',
    measurementId: 'G-VHFZQM9WYR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcvGkWXaVIsOEV4DKgmTYPBv79dDzIrGI',
    appId: '1:1054618276163:android:2fb6d70018654273371ff6',
    messagingSenderId: '1054618276163',
    projectId: 'project-wisata-47148',
    storageBucket: 'project-wisata-47148.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoe4kZJXJuCxAdTxJLB1KsuUt2yUIwYAA',
    appId: '1:1054618276163:ios:d5f8b196baa15212371ff6',
    messagingSenderId: '1054618276163',
    projectId: 'project-wisata-47148',
    storageBucket: 'project-wisata-47148.firebasestorage.app',
    iosClientId: '1054618276163-coh6gqllms3262dga49qmno3vqhj8gqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationWisata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoe4kZJXJuCxAdTxJLB1KsuUt2yUIwYAA',
    appId: '1:1054618276163:ios:d5f8b196baa15212371ff6',
    messagingSenderId: '1054618276163',
    projectId: 'project-wisata-47148',
    storageBucket: 'project-wisata-47148.firebasestorage.app',
    iosClientId: '1054618276163-coh6gqllms3262dga49qmno3vqhj8gqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationWisata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbhYlsfne-z6YCq4_0-Sr0CmIYpKGTHO0',
    appId: '1:1054618276163:web:96129a6fee625364371ff6',
    messagingSenderId: '1054618276163',
    projectId: 'project-wisata-47148',
    authDomain: 'project-wisata-47148.firebaseapp.com',
    storageBucket: 'project-wisata-47148.firebasestorage.app',
    measurementId: 'G-WMMPE99BV1',
  );
}
